spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  redis:
    host: localhost # ${redis_host}
    port: 6379 # ${redis_port}
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # 스키마 자동 생성
    show-sql: true      # SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${G_CLIENT_ID}
            clientSecret: ${G_CLIENT_SECRET}
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${email}
#    password: ${password}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true
#email:
#  sender:
#    man: ${EMAIL}
#    password: ${PASSWORD}
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
#jwt
mail:
  address:
    admin: admin@gmail.com
JWT_KEY: ${JWT_SECRET_KEY}
jwt:
  access-token-expiration-minutes: 30
  #refresh-token-expiration-minutes: 240
MY_ACCESSKEY: ${MY_ACCESSKEY}
MY_SECRETKEY: ${MY_SECRETKEY}
MY_REGION: ${MY_REGION}
EMAIL_MAN: ${EMAIL}
EMAIL_PASSWORD: ${PASSWORD}